# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

job:
  name: ${paths.timestamp}
  # ? Only used to validate the config
  # ? Generates a blank dir, safe to ignore
  num: 1208937
# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${hydra.job.name}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${hydra.job.name}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log
